name: publish

on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
        
    strategy:
      max-parallel: 1
      matrix:
        node-version: [10.x]
      
    steps:
      - name: Set git username and email
        run: |
          #
          git config --global user.email "${{github.actor}}@natwest.com"
          git config --global user.name "${{github.actor}}"
        env:
          GH_USERNAME: ${{ github.event.schedule.user.login }}
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          bump_version_scheme: minor
          release_body: "Version incremented by agent!"
      - run:  |
          #
          git reset --hard
          npm install
          npm test
          npm version patch -m "release by agent" --force
          git add .
          git commit -m "generated"
          git push

