name: publish

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
        
    strategy:
      max-parallel: 1
      matrix:
        node-version: [10.x]
      
    steps:
      - name: Set git username and email
        run: |
          #
          git config --global user.email "${{github.actor}}@natwest.com"
          git config --global user.name "${{github.actor}}"
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run:  |
          #
          npm install
          npm run test
          npm run build
          npm version patch -m "release by agent" --force
          git push --follow-tags
      
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: npm publish --@getify:registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
